### ISSUE TITLE
Python Version Issue

### ISSUE THREAD

**Issue by gis-nlsim** [morinlab/FFPolish#6]
FFPolish appears to be written for version 3.8 (the new := operator was used), but requires version 3.7.8

When I tried to install FFPolish with python version 3.8, I get an error:
Looking for: ['ffpolish', 'python=3.8']
Encountered problems while solving:
  - package ffpolish-0.1.0-py37_1 requires python 3.7.8.*, but none of the providers can be installed

When I installed FFPolish with python version 3.7.8, I get an error when I attempt to use FFPolish
(base) bash-4.4$ conda activate ffpolish
(ffpolish) bash-4.4$ which ffpolish
/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/ffpolish
(ffpolish) bash-4.4$ python --version
Python 3.7.8
(ffpolish) bash-4.4$ ffpolish --help
Traceback (most recent call last):
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/ffpolish", line 5, in <module>
    from filter import filter
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/filter.py", line 11, in <module>
    import vaex
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/__init__.py", line 40, in <module>
    import vaex.dataframe
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/dataframe.py", line 17, in <module>
    import vaex.utils
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/utils.py", line 19, in <module>
    import progressbar
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/progressbar/__init__.py", line 5, in <module>
    from .bar import DataTransferBar
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/progressbar/bar.py", line 13, in <module>
    from python_utils import types
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/python_utils/__init__.py", line 1, in <module>
    from . import (
  File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/python_utils/converters.py", line 89
    if match := regexp.search(input_):
              ^
SyntaxError: invalid syntax

**Comment by ronkesm** [comment]
Also experiencing this issue. Installing a python3.7 compatible version of python_utils breaks other dependencies, so no way to use ffpolish atm.

**Comment by matnguyen** [comment]
> FFPolish appears to be written for version 3.8 (the new := operator was used), but requires version 3.7.8
> 
> When I tried to install FFPolish with python version 3.8, I get an error: Looking for: ['ffpolish', 'python=3.8'] Encountered problems while solving:
> 
> * package ffpolish-0.1.0-py37_1 requires python 3.7.8.*, but none of the providers can be installed
> 
> When I installed FFPolish with python version 3.7.8, I get an error when I attempt to use FFPolish (base) bash-4.4$ conda activate ffpolish (ffpolish) bash-4.4$ which ffpolish /scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/ffpolish (ffpolish) bash-4.4$ python --version Python 3.7.8 (ffpolish) bash-4.4$ ffpolish --help Traceback (most recent call last): File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/ffpolish", line 5, in from filter import filter File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/bin/filter.py", line 11, in import vaex File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/**init**.py", line 40, in import vaex.dataframe File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/dataframe.py", line 17, in import vaex.utils File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/vaex/utils.py", line 19, in import progressbar File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/progressbar/**init**.py", line 5, in from .bar import DataTransferBar File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/progressbar/bar.py", line 13, in from python_utils import types File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/python_utils/**init**.py", line 1, in from . import ( File "/scratch/users/astar/gis/simngl/apps/bcbio/v129/anaconda/envs/ffpolish/lib/python3.7/site-packages/python_utils/converters.py", line 89 if match := regexp.search(input_): ^ SyntaxError: invalid syntax

Hi there, sorry for the delay. This is interesting as FFPolish was definitly developed on Python 3.7. Must be a dependency issue. I'll take a look and get back to you when it is functional again.

**Comment by matnguyen** [comment]
@ronkesm @gis-nlsim I have addressed this issue on #7. I will also work to create a functioning conda package, however am having issues with conda as it cannot feasibly solve the environment while mamba can (as used in the docker container). Let me know how the docker container works for you.

**Comment by ronkesm** [comment]
Hi @matnguyen, thanks for actioning this so promptly. The docker container worked as expected. Haven't had any issues.
