### ISSUE TITLE
Unable to install FFPolish using conda

### ISSUE THREAD

**Issue by kiranchari** [morinlab/FFPolish#7]
I am trying to install FFPolish using conda v22.9 (conda install -c matnguyen ffpolish) but it keeps loading for a long time without success (see output below). I have tried installing on it different machines without success. I believe my conda installation is fine as I use it without issues otherwise.

```
$ conda install -c matnguyen ffpolish
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
```

I have the necessary channels configured:
```
$ conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults

```

Is it possible to directly download the FFPolish repository from Github and install using this script: https://github.com/morinlab/FFPolish/blob/master/conda/build.sh?

**Comment by matnguyen** [comment]
As an alternative, I have made a docker container (`docker pull matnguyen/ffpolish`). It appears that there was an issue with the Vaex version, so that is fixed in the docker container. If you want to build from scratch, I recommend using the following package versions that I used for the docker container: 

```
    bam-readcount=1.0.1 
    bedops=2.4.39 
    convert_zero_one_based=0.0.1 
    numpy=1.21.6 
    pandas=1.1.3 
    pysam=0.16.0 
    python=3.7 
    scikit-learn=0.23.2 
    tqdm=4.50.2 
    vaex-core=4.14.0
```

Let me know how the docker container works for you

**Comment by kiranchari** [comment]
Thanks @matnguyen. The docker image works but the pull command should be `docker pull matnguyen/ffpolish:0.1.0` as there is no 'latest' tag in https://hub.docker.com/r/matnguyen/ffpolish
