### ISSUE TITLE
Original training data is missing for retraining mode

### ISSUE THREAD

**Issue by yuew10** [morinlab/FFPolish#8]
I'm trying to run `ffpolish filter` with `--rt train.hdf5` which has been generated by `ffpolish extract`. However, the original training data is missing. 

From file `.../envs/ffpolish/lib/filter.py`, 
Line 31   `orig_train_df = vaex.open(os.path.join(BASE, 'orig_train.hdf5'))`
```
OSError: Could not open file: .../envs/ffpolish/orig_train.hdf5, it does not exist
```

**Comment by matnguyen** [comment]
Hi @yuew10 

The training data can be downloaded here: https://www.bcgsc.ca/downloads/morinlab/FFPolish/
In the meantime, I will update the code to automatically download and use the training data
